### ISSUE TITLE
feat: Longhand syntax for merge and override

### ISSUE THREAD

**Issue by lokesh** [privatenumber/vue-vnode-syringe#2]
I wasn't able to intuit the meaning of the & and ! modifiers at first glance. What do you think about supporting a more verbose syntax for the 'modifiers' as well? 

I don't know if it's feasible to add modifiers narrowly to this component's props.

```
class.merge="..."
class&="..."

class.override="..."
class!="..."
```

Similar in philosophy to:
```
v-bind:class="..."
:class=""

 v-on:click="..."
@click="..."
```

**Comment by privatenumber** [comment]
I agree the syntax isn't super clear.

I initially wanted to use the directive style "modifier" syntax as well (eg. `:attr.modifier="value"`), but it gets parsed out by Vue because it gets interpreted as a modifier. [Demo](https://jsfiddle.net/hirokiosame/mnr4w7oz/1/)

Open to other syntax ideas if you have any.

Just updated the docs though. Hope that makes it clearer.

**Comment by lokesh** [comment]
Bummer about not being able to add custom "modifier"s, but no biggie. The doc updates you made help call out the merge strategies and their associated syntax.
